version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0


workflows:
  build-test-deploy:
    jobs:
      # - build
      # - test:
      #     requires:
      #       - build
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: aws-ecr-demo
          tag: "$CIRCLE_SHA1"
      #     requires:
      #       - test
      - deploy_to_staging:
          requires:
            - aws-ecr/build-and-push-image

configure_awscloud: &configure_awscloud
  run:
    name: configure awscloud default settings
    command: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install
      aws --version
      echo $AWS_SECRET_ACCESS_KEY
      echo $AWS_ACCESS_KEY_ID
      aws configure

install_ansible: &install_ansible
  run:
    name: install ansible
    command: |
      apt-get update && apt-get install python3-pip curl unzip -y
      pip3 install ansible openshift

deploy_to_kubernetes: &deploy_to_kubernetes
  run:
    name: Run ansible playbook to configure kubernetes
    command: |
      if [[ "$CIRCLE_BRANCH" == 'develop' ]] ; then
        aws eks --region AWS_REGION update-kubeconfig --name staging
      
      if [[ "$CIRCLE_BRANCH" == 'master' ]] ; then
        aws eks --region AWS_REGION update-kubeconfig --name staging #change to production

      kubectl cluster-info
      ansible-playbook ansible/main.yml -vvv


jobs:
  build:
    docker:
      - image: circleci/node:9.11.2-stretch
    steps:
      - checkout
      - run:
          name: install dependency
          command: |
            npm install --production

  test:
    docker:
      - image: circleci/node:9.11.2-stretch
    steps:
      - checkout
      - run:
          name: install dependency
          command: |
            npm install --production

  deploy_to_staging:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - *install_ansible
      - *configure_awscloud
      - *deploy_to_kubernetes
