---
ansible_python_interpreter: "/usr/bin/python3"
AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
AWS_REGION: "{{ lookup('env', 'AWS_REGION')}}"
AWS_ECR_ACCOUNT_URL: "{{ lookup('env', 'AWS_ECR_ACCOUNT_URL')}}"
DEPLOYMENT_IMAGE: "{{ lookup('env'. 'DEPLOYMENT_IMAGE')}}"
CIRCLE_WORKING_DIRECTORY: "{{ lookup('env', 'CIRCLE_WORKING_DIRECTORY')}}"
