---
ansible_python_interpreter: "/usr/bin/python3"
AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
AWS_REGION: "{{ lookup('env', 'AWS_REGION')}}"
AWS_ECR_ACCOUNT_URL: "{{ lookup('env', 'AWS_ECR_ACCOUNT_URL')}}"
CIRCLE_WORKING_DIRECTORY: "{{ lookup('env', 'CIRCLE_WORKING_DIRECTORY')}}"
OBJECT_FILE_DIR: "{{ CIRCLE_WORKING_DIRECTORY }}/admin"
DEPLOYMENT_IMAGE: "{{ DEPLOYMENT_IMAGE }}"